[package]
name = "iron_sandboxide"
version = "0.1.1"
authors = ["CJ McAllister <cjm571@gmail.com>"]

[dependencies]
cast_iron = { path = "../cast_iron", version = "0.1.2" }
lazy_static = "1.2.0"
ggez = "0.5.1"