[package]
name = "sand_casting"
version = "0.6.9"
authors = ["CJ McAllister <cjm571@gmail.com>"]

[dependencies]
cast_iron = { path = "../cast_iron", version = "^0.9" }
chrono = { version = "0.4", features = ["serde"] }
ggez = "0.5.1"
mt_logger = "^2"
rand = "0.7.3"
variant_count = "*"